const HUMOR_POST_MESSAGES: ReadonlyArray<string> = [
  "Aujourd'hui, j'ai appris que la résilience se mesure en KPI.",
  "Mon café du matin a plus de leadership que mon équipe projet.",
  "Je ne procrastine pas, je fais du benchmark concurrentiel intérieur.",
  "Nouvelle compétence : transformer un doute en roadmap trimestrielle.",
  "Mon plan de carrière tient sur un post-it et beaucoup de conviction.",
  "On m'a dit de penser hors cadre, j'ai exporté le cadre en PDF.",
  "Le networking, c'est du speed dating avec des slides.",
  "Je transforme chaque erreur en apprentissage... puis en carrousel.",
  "Objectif Q2 : paraître organisé même quand Notion panique.",
  "J'optimise ma vie perso avec un tableau Kanban affectif.",
  "J'ai remplacé mon syndrome de l'imposteur par un abonnement Premium. ✨",
  "Ne dites plus 'burn-out', dites 'incubation spirituelle intensive'. 🙏",
  "Mon chat a une meilleure stratégie de Personal Branding que vous. 🐾",
  "Rien de tel qu'une réunion de 2h pour décider de la couleur d'un bouton. 🚀",
  "J'ai pitché mon petit-déjeuner. Le granola a levé 2 millions. 💡",
  "La vulnérabilité est un levier de croissance, si elle est bien marketée. 📈",
  "Je ne suis pas en retard, je suis en phase d'idéation asynchrone.",
  "Ma plus grande réussite ? Avoir survécu à un lundi sans Story LinkedIn.",
  "Le succès, c'est 1% de talent et 99% de police Montserrat en gras.",
  "J'ai transformé mon licenciement en 'opportunité de pivot stratégique'.",
  "Le silence est d'or, mais le bruit numérique génère des leads. 📣",
  "Je traite mes vacances comme un sprint agile : repos forcé à 110%.",
  "Mon mindset est tellement disruptif que je ne me comprends plus moi-même.",
  "L'échec n'existe pas, c'est juste un feedback non sollicité de l'univers. ✨",
  "J'ai atteint l'alignement chakras-objectifs annuels. Namasté le ROI. 🙏",
  "Un café, un post, un mensonge bienveillant : la routine des champions.",
  "Je ne cherche pas un job, je cherche une aventure humaine avec des tickets restos.",
  "Ma boîte mail est un cimetière de 'Je reviens vers vous rapidement'.",
  "Entrepreneur : nom masculin signifiant 'ne dort pas pour payer des SaaS'.",
  "J'ai lu 52 livres en une semaine. Enfin, j'ai lu les résumés sur Medium.",
  "Le télétravail m'a appris que mon frigo est mon meilleur collaborateur.",
  "Mon équipe est une famille. Une famille qui fait des feedbacks à 21h.",
  "J'ai tracké mon sommeil sur Excel. Ma nuit est en sous-performance. 📊",
  "On ne dit plus 'problème technique', mais 'challenge d'infrastructure créative'.",
  "La bienveillance corporate s'arrête là où le tableur Excel commence.",
  "J'ai fait un TedX dans ma douche. L'audience était conquise. 🚿",
  "Le personal branding, c'est l'art de se féliciter d'avoir bu de l'eau. ✨",
  "Ma résilience est telle que je réponds aux mails dans mes rêves. 🚀",
  "J'ai automatisé mon empathie avec un outil No-Code. Gain de temps fou.",
  "Inspirer les autres est mon job à plein temps. Le reste, c'est de l'admin.",
  "Je ne fais pas de politique de bureau, je fais de la diplomatie d'open space.",
  "L'agilité, c'est changer d'avis juste avant la deadline. 🏃‍♂️",
  "J'ai remplacé ma conscience par un algorithme d'optimisation de reach.",
  "Ma vision à 5 ans ? Survivre jusqu'à vendredi prochain. 🙏",
  "Le futur appartient à ceux qui se lèvent tôt pour poster des citations. 🌅",
  "Un call de 5 minutes qui dure 1 heure : c'est ça, la magie du collectif.",
  "J'ai transformé ma fatigue en 'énergie de transformation radicale'.",
  "Mon elevator pitch a coincé l'ascenseur. C'est ça, l'impact. 💥",
  "Ne cherchez pas le bonheur, cherchez la scalabilité de vos émotions. 📈",
  "Je suis Chief Happiness Officer de ma propre solitude. ✨",
  "Le 'Deep Work', c'est quand j'oublie de regarder Instagram pendant 12 minutes.",
  "J'ai pivoté mon mindset : je ne suis plus au chômage, je suis en 'Side Project permanent'.",
  "Ma stratégie de contenu ? Dire des évidences avec un ton prophétique.",
  "Le leadership, c'est savoir déléguer ses propres erreurs. 💡",
  "J'ai fait un burn-out 2.0 : c'est comme le premier, mais avec un podcast.",
  "La passion est le moteur, mais le virement bancaire est le carburant.",
  "J'ai analysé mes échecs. Verdict : c'était la faute de l'algorithme.",
  "Rien ne dit 'je t'aime' comme un message Slack envoyé un dimanche. ❤️",
  "Je suis en train de disrupter mon propre sommeil. Objectif 0 minute.",
  "Le sens de la vie se trouve quelque part entre la ligne 45 et 46 d'un CSV. 🔍",
  "J'ai recruté un stagiaire pour gérer mon humilité sur les réseaux.",
  "La vraie liberté, c'est de pouvoir refuser un webinar sur le Growth Hacking.",
  "Je ne suis pas têtu, je suis en 'hyper-focus sur une vision non validée'.",
  "Mon égo est en mode SaaS : plus il y a d'utilisateurs, plus il grimpe. 🚀",
  "L'authenticité est ma valeur n°1 (voir conditions générales en PJ). ✨",
  "J'ai transformé ma pause déjeuner en session de networking thérapeutique.",
  "Le succès laisse des traces, surtout des cernes sous les yeux. 🙏",
  "Je n'ai pas de problèmes, j'ai des 'opportunités de déploiement de solutions'.",
  "Ma Morning Routine commence par 2h de culpabilité productive.",
  "L'innovation, c'est mettre 'IA' dans le nom d'un fichier Excel. 🤖",
  "J'ai pitché mon chat. Il a refusé l'equity. Quel leader. 🐱",
  "Le storytelling, c'est l'art de rendre passionnant un tri de dossiers. 📖",
  "J'ai optimisé mon temps de parole. Je ne dis plus que des punchlines.",
  "Mon CV est une œuvre de fiction approuvée par la critique. ✨",
  "Le bonheur au travail commence par une machine à café qui fonctionne.",
  "Je ne suis pas stressé, je suis en haute fréquence vibratoire business. 📈",
  "J'ai créé un écosystème autour de ma procrastination. C'est brillant.",
  "Le mindset 'Day 1' c'est bien, mais le mindset 'Pay Day' c'est mieux. 💰",
  "J'ai transformé une insomnie en article sur la 'disruption du repos'.",
  "Ma zone de confort est devenue un espace de co-working.",
  "Le networking, c'est comme la pêche, mais on attrape des cartes de visite.",
  "J'ai atteint mon quota de 'synergie' pour l'année. Rendez-vous en 2027.",
  "L'important n'est pas de participer, mais de taguer 20 personnes sur la photo.",
  "Je ne suis pas multitâche, je suis juste partout et nulle part à la fois.",
  "Mon intuition est mon meilleur Business Plan. Elle est assez floue pour réussir.",
  "J'ai fait une retraite spirituelle sur Zoom. J'en suis ressorti avec un PDF. ✨",
  "Le management bienveillant, c'est dire 'merci' avant de demander l'impossible. 🙏",
  "J'ai automatisé mon bonheur. Les résultats sont stables à 2%.",
  "On ne dit plus 'perdre son temps', on dit 'explorer des verticales improbables'.",
  "Ma vision est si grande que même l'écran 27 pouces ne suffit plus. 🚀",
  "J'ai appris la patience en attendant que le logo Slack arrête de sauter. 💡",
  "Le Growth Hacking de mon âme avance bien. Reach en hausse de 15%.",
  "J'ai transformé mon appartement en incubateur de rêves et de vaisselle sale.",
  "L'avenir appartient à ceux qui maîtrisent l'art du point virgule en fin de mail. ;",
  "Je ne suis pas au chômage, je suis en 'période d'incubation de génie'.",
  "Mon leadership est inclusif : j'inclus tout le monde dans ma fatigue. 😴",
  "J'ai optimisé mon empathie pour qu'elle tienne en 280 caractères.",
  "Le succès, c'est quand ton nom devient un verbe dans une réunion. 🚀",
  "J'ai enfin trouvé mon 'Pourquoi'. C'était écrit sur mon bulletin de paie. ✨",
  "Je suis le CEO de ma propre incertitude. Et les parts augmentent. 🙏",
  "Ma quête de sens s'est arrêtée net devant le prix de l'abonnement ChatGPT Plus. ✨",
];

export function getRandomHumorPostMessage(): string {
  const randomIndex = Math.floor(Math.random() * HUMOR_POST_MESSAGES.length);
  return HUMOR_POST_MESSAGES[randomIndex];
}
