const HUMOR_POST_MESSAGES: ReadonlyArray<string> = [
  "Aujourd'hui, j'ai appris que la résilience se mesure en KPI.",
  "Mon café du matin a plus de leadership que mon équipe projet.",
  "Je ne procrastine pas, je fais du benchmark concurrentiel intérieur.",
  "Nouvelle compétence : transformer un doute en roadmap trimestrielle.",
  "Mon plan de carrière tient sur un post-it et beaucoup de conviction.",
  "On m'a dit de penser hors cadre, j'ai exporté le cadre en PDF.",
  "Le networking, c'est du speed dating avec des slides.",
  "Je transforme chaque erreur en apprentissage... puis en carrousel.",
  "Objectif Q2 : paraître organisé même quand Notion panique.",
  "J'optimise ma vie perso avec un tableau Kanban affectif.",
  "J'ai remplacé mon syndrome de l'imposteur par un abonnement Premium. ✨",
  "Ne dites plus 'burn-out', dites 'incubation spirituelle intensive'. 🙏",
  "Mon chat a une meilleure stratégie de Personal Branding que vous. 🐾",
  "Rien de tel qu'une réunion de 2h pour décider de la couleur d'un bouton. 🚀",
  "J'ai pitché mon petit-déjeuner. Le granola a levé 2 millions. 💡",
  "La vulnérabilité est un levier de croissance, si elle est bien marketée. 📈",
  "Je ne suis pas en retard, je suis en phase d'idéation asynchrone.",
  "Ma plus grande réussite ? Avoir survécu à un lundi sans Story LinkedIn.",
  "Le succès, c'est 1% de talent et 99% de police Montserrat en gras.",
  "J'ai transformé mon licenciement en 'opportunité de pivot stratégique'.",
  "Le silence est d'or, mais le bruit numérique génère des leads. 📣",
  "Je traite mes vacances comme un sprint agile : repos forcé à 110%.",
  "Mon mindset est tellement disruptif que je ne me comprends plus moi-même.",
  "L'échec n'existe pas, c'est juste un feedback non sollicité de l'univers. ✨",
  "J'ai atteint l'alignement chakras-objectifs annuels. Namasté le ROI. 🙏",
  "Un café, un post, un mensonge bienveillant : la routine des champions.",
  "Je ne cherche pas un job, je cherche une aventure humaine avec des tickets restos.",
  "Ma boîte mail est un cimetière de 'Je reviens vers vous rapidement'.",
  "Entrepreneur : nom masculin signifiant 'ne dort pas pour payer des SaaS'.",
  "J'ai lu 52 livres en une semaine. Enfin, j'ai lu les résumés sur Medium.",
  "Le télétravail m'a appris que mon frigo est mon meilleur collaborateur.",
  "Mon équipe est une famille. Une famille qui fait des feedbacks à 21h.",
  "J'ai tracké mon sommeil sur Excel. Ma nuit est en sous-performance. 📊",
  "On ne dit plus 'problème technique', mais 'challenge d'infrastructure créative'.",
  "La bienveillance corporate s'arrête là où le tableur Excel commence.",
  "J'ai fait un TedX dans ma douche. L'audience était conquise. 🚿",
  "Le personal branding, c'est l'art de se féliciter d'avoir bu de l'eau. ✨",
  "Ma résilience est telle que je réponds aux mails dans mes rêves. 🚀",
  "J'ai automatisé mon empathie avec un outil No-Code. Gain de temps fou.",
  "Inspirer les autres est mon job à plein temps. Le reste, c'est de l'admin.",
  "Je ne fais pas de politique de bureau, je fais de la diplomatie d'open space.",
  "L'agilité, c'est changer d'avis juste avant la deadline. 🏃‍♂️",
  "J'ai remplacé ma conscience par un algorithme d'optimisation de reach.",
  "Ma vision à 5 ans ? Survivre jusqu'à vendredi prochain. 🙏",
  "Le futur appartient à ceux qui se lèvent tôt pour poster des citations. 🌅",
  "Un call de 5 minutes qui dure 1 heure : c'est ça, la magie du collectif.",
  "J'ai transformé ma fatigue en 'énergie de transformation radicale'.",
  "Mon elevator pitch a coincé l'ascenseur. C'est ça, l'impact. 💥",
  "Ne cherchez pas le bonheur, cherchez la scalabilité de vos émotions. 📈",
  "Je suis Chief Happiness Officer de ma propre solitude. ✨",
  "Le 'Deep Work', c'est quand j'oublie de regarder Instagram pendant 12 minutes.",
  "J'ai pivoté mon mindset : je ne suis plus au chômage, je suis en 'Side Project permanent'.",
  "Ma stratégie de contenu ? Dire des évidences avec un ton prophétique.",
  "Le leadership, c'est savoir déléguer ses propres erreurs. 💡",
  "J'ai fait un burn-out 2.0 : c'est comme le premier, mais avec un podcast.",
  "La passion est le moteur, mais le virement bancaire est le carburant.",
  "J'ai analysé mes échecs. Verdict : c'était la faute de l'algorithme.",
  "Rien ne dit 'je t'aime' comme un message Slack envoyé un dimanche. ❤️",
  "Je suis en train de disrupter mon propre sommeil. Objectif 0 minute.",
  "Le sens de la vie se trouve quelque part entre la ligne 45 et 46 d'un CSV. 🔍",
  "J'ai recruté un stagiaire pour gérer mon humilité sur les réseaux.",
  "La vraie liberté, c'est de pouvoir refuser un webinar sur le Growth Hacking.",
  "Je ne suis pas têtu, je suis en 'hyper-focus sur une vision non validée'.",
  "Mon égo est en mode SaaS : plus il y a d'utilisateurs, plus il grimpe. 🚀",
  "L'authenticité est ma valeur n°1 (voir conditions générales en PJ). ✨",
  "J'ai transformé ma pause déjeuner en session de networking thérapeutique.",
  "Le succès laisse des traces, surtout des cernes sous les yeux. 🙏",
  "Je n'ai pas de problèmes, j'ai des 'opportunités de déploiement de solutions'.",
  "Ma Morning Routine commence par 2h de culpabilité productive.",
  "L'innovation, c'est mettre 'IA' dans le nom d'un fichier Excel. 🤖",
  "J'ai pitché mon chat. Il a refusé l'equity. Quel leader. 🐱",
  "Le storytelling, c'est l'art de rendre passionnant un tri de dossiers. 📖",
  "J'ai optimisé mon temps de parole. Je ne dis plus que des punchlines.",
  "Mon CV est une œuvre de fiction approuvée par la critique. ✨",
  "Le bonheur au travail commence par une machine à café qui fonctionne.",
  "Je ne suis pas stressé, je suis en haute fréquence vibratoire business. 📈",
  "J'ai créé un écosystème autour de ma procrastination. C'est brillant.",
  "Le mindset 'Day 1' c'est bien, mais le mindset 'Pay Day' c'est mieux. 💰",
  "J'ai transformé une insomnie en article sur la 'disruption du repos'.",
  "Ma zone de confort est devenue un espace de co-working.",
  "Le networking, c'est comme la pêche, mais on attrape des cartes de visite.",
  "J'ai atteint mon quota de 'synergie' pour l'année. Rendez-vous en 2027.",
  "L'important n'est pas de participer, mais de taguer 20 personnes sur la photo.",
  "Je ne suis pas multitâche, je suis juste partout et nulle part à la fois.",
  "Mon intuition est mon meilleur Business Plan. Elle est assez floue pour réussir.",
  "J'ai fait une retraite spirituelle sur Zoom. J'en suis ressorti avec un PDF. ✨",
  "Le management bienveillant, c'est dire 'merci' avant de demander l'impossible. 🙏",
  "J'ai automatisé mon bonheur. Les résultats sont stables à 2%.",
  "On ne dit plus 'perdre son temps', on dit 'explorer des verticales improbables'.",
  "Ma vision est si grande que même l'écran 27 pouces ne suffit plus. 🚀",
  "J'ai appris la patience en attendant que le logo Slack arrête de sauter. 💡",
  "Le Growth Hacking de mon âme avance bien. Reach en hausse de 15%.",
  "J'ai transformé mon appartement en incubateur de rêves et de vaisselle sale.",
  "L'avenir appartient à ceux qui maîtrisent l'art du point virgule en fin de mail. ;",
  "Je ne suis pas au chômage, je suis en 'période d'incubation de génie'.",
  "Mon leadership est inclusif : j'inclus tout le monde dans ma fatigue. 😴",
  "J'ai optimisé mon empathie pour qu'elle tienne en 280 caractères.",
  "Le succès, c'est quand ton nom devient un verbe dans une réunion. 🚀",
  "J'ai enfin trouvé mon 'Pourquoi'. C'était écrit sur mon bulletin de paie. ✨",
  "Je suis le CEO de ma propre incertitude. Et les parts augmentent. 🙏",
  "Ma quête de sens s'est arrêtée net devant le prix de l'abonnement ChatGPT Plus. ✨",
];

const NEWS_ITEMS: ReadonlyArray<string> = [
  'Productivité : travailler 4 minutes de moins par jour offre 1 an de vie en plus.',
  'Recrutement : 78% des candidats préfèrent un baby-foot à une mutuelle.',
  'Management : l’usage du mot "synergie" a chuté de 12% au profit de "mindset".',
  'Engagement : poster à 4h12 du matin augmente le reach de 45% chez les insomniaques.',
  'Data : 90% des graphiques sur LinkedIn sont dessinés à main levée.',
  'RH : l’absence de ponctuation dans les emails réduit le stress de 8%.',
  'Vente : dire "je reviens vers vous" multiplie par deux les chances d’oubli.',
  'Économie : le prix du "like" stagne malgré l’inflation des superlatifs.',
  'Networking : un café virtuel de 15 min équivaut à 3 ans d’amitié réelle.',
  'Étude : les bureaux en open-space favorisent l’usage du casque antibruit (+90%).',
  'Le "Slow-Scrolling" : la nouvelle méthode pour méditer devant son fil d’actualité.',
  'Le "Ghost-Leading" : diriger une équipe sans jamais répondre sur Slack.',
  'Trend : le "Micro-Tasking" ou l’art de découper une tâche simple en 50 réunions.',
  'Focus : le "Deep Work" remplacé par le "Deep Lunch" pour souder les équipes.',
  'Innovation : le "Reverse Mentoring" où les stagiaires apprennent à scroller aux seniors.',
  'Agilité : le passage à la méthode "Scrum-Vibe" pour prioriser au feeling.',
  'Concept : le "Wellness-Washing", ou l’art d’offrir des pommes pour masquer un burnout.',
  'Le "Prompt-Bragging" : copier-coller du ChatGPT sans même retirer les guillemets.',
  'Marketing : le "Emotional B2B" pour faire pleurer les acheteurs de photocopieurs.',
  'Le "Quiet Resigning" des algorithmes : quand ton post ne fait que 2 vues.',
  'Insolite : il réussit à lever 2 millions sans avoir de concept, juste un logo néon.',
  'Révolution : une entreprise remplace ses managers par des Golden Retrievers.',
  'Inclusion : les profils sans photo de profil sont désormais invisibles, littéralement.',
  'Sommet du vide : une conférence sur le silence affiche complet sur Zoom.',
  'Bio LinkedIn : ajouter "Astronaute de la pensée" augmente les demandes de connexion.',
  'Performance : il répond à ses mails en dormant grâce à l’hypnose managériale.',
  'Écologie : supprimer ses mails non lus sauve 0,00001 pingouin par décennie.',
  'Recrutement : tester le QI des candidats via leur choix de police d’écriture.',
  'Psychologie : le syndrome de l’imposteur est désormais une compétence recherchée.',
  'Logistique : livrer des idées avant qu’elles ne soient conçues, le futur du conseil.',
  'Algorithme : mettre un emoji "fusée" annule l’effet d’une mauvaise syntaxe.',
  'Shadowban : utiliser le mot "salaire" divise votre visibilité par quatre.',
  'Reach : les posts parlant de résilience sont 5 fois plus partagés le lundi.',
  'Visibilité : ne rien dire en 10 paragraphes reste la stratégie n°1 de 2026.',
  'Engagement : le bouton "Célébrer" est désormais plus utilisé que le bouton "Réfléchir".',
  'Nouveauté : LinkedIn teste le bouton "On s’en fout" en version bêta.',
  'SEO : s’appeler "Jean-IA" booste les apparitions dans les recherches de 300%.',
  'Feed : l’ordre des posts est maintenant géré par une intelligence artificielle dépressive.',
  'Influence : 12 likes d’un CEO valent 1000 likes de stagiaires (en valeur boursière).',
  'Le carrousel infini : le nouveau format qui ne s’arrête jamais vraiment.',
  'Flex office : premier arrivé, premier assis, dernier survivant.',
  'Burnout : renommé "Période d’incubation créative" par la French Tech.',
  'Télétravail : 45% des réunions Zoom sont suivies en bas de pyjama.',
  'Congés : les vacances illimitées, ou comment ne plus jamais oser s’arrêter.',
  'Culture : le tutoiement obligatoire réduit la hiérarchie mais augmente l’anxiété.',
  'Candidature : envoyer son CV en format NFT pour prouver son inutilité.',
  'Entretien : "Où vous voyez-vous dans 5 ans ?" "En burn-out, comme tout le monde."',
  'Freelance : être son propre patron, c’est avoir le pire patron du monde.',
  'Offre d’emploi : recherche "Ninja du Excel" pour faire des additions.',
  'Séminaire : 100% des participants préféreraient être chez eux devant Netflix.',
  'Identité : changer sa photo de profil tous les 3 jours pour simuler une évolution.',
  'Ego : 1 clic sur 2 sur LinkedIn est une vérification de ses propres vues.',
  'Storytelling : transformer une chute de vélo en leçon de management agile.',
  'Authenticité : utiliser un filtre "naturel" pour cacher sa fatigue de solopreneur.',
  'Influenceurs : ils lancent une formation pour vendre des formations de formation.',
  'Réseau : avoir 30 000 contacts et ne connaître personne pour de vrai.',
  'Leadership : parler fort en réunion compte désormais comme une vision stratégique.',
  'Personal Branding : porter un col roulé noir augmente votre crédibilité de 20%.',
  'Networking : le "Pitch Ascenseur" désormais pratiqué dans les escaliers pour durer.',
  'Inspiration : 100% des citations de Steve Jobs sur le feed sont apocryphes.',
  'IA : une start-up invente un robot qui s’excuse à votre place pour le retard.',
  'Web3 : le métavers des bureaux vides attire déjà 0 visiteur par jour.',
  'Blockchain : certifier son diplôme de "Meilleur collègue" sur l’Ethereum.',
  'Transhumanisme : une puce pour scroller LinkedIn directement dans la rétine.',
  'Cyber-sécurité : changer son mot de passe pour "123456" reste la norme RH.',
  'Green IT : éteindre son écran pendant la pause déjeuner sauve la planète.',
  'Big Data : on sait ce que vous allez poster avant même que vous ne soyez inspiré.',
  'No-Code : construire une licorne sans savoir aligner trois lignes de CSS.',
  'SaaS : une application pour gérer les applications de gestion des tâches.',
  'Hardware : le retour du Minitel pour un networking plus "authentique".',
  'Chief Happiness Officer : désormais armé d’un lance-pierres à bonbons.',
  'Onboarding : le kit de bienvenue contient désormais une pierre de lithothérapie.',
  'RSE : planter un arbre virtuel pour compenser 400 allers-retours en jet.',
  'Feed-back : le "sandwich de compliments" est remplacé par le "toast de reproches".',
  'Brainstorming : 4 heures de post-it pour finir sur l’idée du stagiaire ignorée.',
  'Hiérarchie : le "Flat Management" où tout le monde décide mais personne n’est responsable.',
  'Valeurs : "Bienveillance" devient le mot le plus tagué et le moins appliqué.',
  'Recrutement : le test de personnalité remplace l’expérience métier.',
  'Mobilité : changer de chaise de bureau compte comme une promotion interne.',
  'Work-Life Balance : travailler le dimanche mais avec une plante verte à côté.',
  'Méta : ce post a été généré par une IA pour amuser d’autres IA.',
  'Paradoxe : moins on a de choses à dire, plus le post est long.',
  'Sondage : 99% des gens répondent au hasard pour voir les résultats.',
  'Analyse : le temps passé à lire des news bullshit dépasse le temps de travail.',
  'Étude de marché : le marché du vent se porte bien (+200% de croissance).',
  'Algorithme : le bouton "En savoir plus" cache souvent qu’il n’y a rien de plus.',
  'Réseau : être tagué dans un post de 50 personnes est le nouveau spam.',
  'Visibilité : les majuscules dans le titre divisent par deux le QI perçu.',
  'Tendance : le retour au papier pour éviter les notifications de Jean-Expert.',
  'Fin de partie : LinkedIn annonce la suppression des profils "Guru".',
  'Bien-être : la méditation en réunion Zoom permet de dormir les yeux ouverts.',
  'Productivité : le "Multi-tasking" fait baisser le QI plus vite que le cannabis.',
  'Start-up : transformer une application de météo en réseau social décentralisé.',
  'Expertise : être expert en "rien" permet d’être consultant en "tout".',
  'Confiance : 100% des gens qui disent "C’est disruptif" ne savent pas ce que ça veut dire.',
  'Insolite : il démissionne en envoyant un seul emoji "peace", l’action grimpe.',
  'Marketing : vendre de l’eau tiède en disant qu’elle est "bio-dynamisée".',
  'Carrière : gravir les échelons en étant simplement "le moins pire".',
  'Psychologie : le FOMO de ne pas voir un post sur la résilience touche 12% des cadres.',
  'Conclusion : la lecture de cette liste a augmenté votre bullshit-score de 5 points.'
];

export function getRandomHumorPostMessage(): string {
  const randomIndex = Math.floor(Math.random() * HUMOR_POST_MESSAGES.length);
  return HUMOR_POST_MESSAGES[randomIndex];
}

export function getRandomNewsItems(count = 3): ReadonlyArray<string> {
  const shuffledNewsItems = [...NEWS_ITEMS];

  for (let index = shuffledNewsItems.length - 1; index > 0; index -= 1) {
    const randomIndex = Math.floor(Math.random() * (index + 1));
    [shuffledNewsItems[index], shuffledNewsItems[randomIndex]] = [
      shuffledNewsItems[randomIndex],
      shuffledNewsItems[index],
    ];
  }

  return shuffledNewsItems.slice(0, Math.min(count, shuffledNewsItems.length));
}
